
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcd_orderservice
    username: root
    password: 123456
  application:
    name: order-service



mybatis-plus:
  global-config:
    db-config:
      table-prefix: tcd_
server:
  port: 8080
