
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://175.27.191.217:3306/dcd_answering_lottery?&useSSL=false
    username: root
    password: MLY59420s@




mybatis-plus:
  global-config:
    db-config:
      table-prefix: tcd_
server:
  port: 8080
