
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.27.191.217:3306/dcd_orderservice
    username: root
    password: MLY59420s@
  application:
    name: order-service

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tcd_
server:
  port: 8080
