
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my-test?&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tcd_
server:
  port: 8888